# Generated by Django 3.1.6 on 2021-04-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucset', '0002_auto_20210328_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fullplot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.DateField(blank=True, null=True)),
                ('good', models.FloatField(blank=True, db_column='Good', null=True)),
                ('bad', models.FloatField(blank=True, db_column='Bad', null=True)),
                ('recommend', models.TextField(blank=True, db_column='Recommend', null=True)),
            ],
            options={
                'db_table': 'Fullplot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subplots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('score', models.FloatField(blank=True, db_column='Score', null=True)),
                ('profit', models.FloatField(blank=True, db_column='Profit', null=True)),
                ('variances', models.FloatField(blank=True, db_column='Variances', null=True)),
            ],
            options={
                'db_table': 'Subplots',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SucsetFinance',
        ),
    ]
